apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.rails.service: drkiq
  name: drkiq
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.rails.service: drkiq
status:
  loadBalancer: {}
