apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: drkiq-postgres
  name: drkiq-postgres
spec:
  storageClassName: manual
  selector:
    matchLabels:
      volume-type: postgres
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

