kind: PersistentVolume
apiVersion: v1
metadata:
  name: proj
  labels:
    type: local
    volume-type: proj
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/drkiq/"
