apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.rails.service: drkiq
  name: drkiq
spec:
  storageClassName: manual
  selector:
    matchLabels:
      volume-type: drkiq
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
