kind: PersistentVolume
apiVersion: v1
metadata:
  name: drkiq-redis
  labels:
    type: local
    volume-type: redis
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/drkiq-redis/"
