apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.rails.service: drkiq-redis
  name: drkiq-redis
spec:
  storageClassName: manual
  selector:
    matchLabels:
      volume-type: redis
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
