kind: PersistentVolume
apiVersion: v1
metadata:
  name: drkiq-postgres
  labels:
    type: local
    volume-type: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/drkiq-postgres/"
